### ISSUE TITLE
Numpy requirement not really neccesary

### ISSUE THREAD

**Issue by janEntikan** [Germanunkol/CCD-IK-Panda3D#1]
https://github.com/Germanunkol/CCD-IK-Panda3D/blob/c771100cfabd2cbfcc7bfd7130399159cbeadd04/CCDIK/VecUtils.py#L189

Numpy is a relatively heavy requirement only to get a reference to `inf`.
You can get this by doing `float('inf')` as well as `math.inf`.

**Comment by Germanunkol** [comment]
Very true, I think I was planning on using numpy for other things as well at the time.

Will try to remove it.
